[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Configuración para Next.js con export estático
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración para rutas dinámicas
[[redirects]]
  from = "/jugadores/:id"
  to = "/jugadores/[id].html"
  status = 200

[[redirects]]
  from = "/partidos/:categoria"
  to = "/partidos/[categoria].html"
  status = 200

# Headers para seguridad y PWA
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuración para PWA
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Variables de entorno para producción
[context.production.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

# Configuración para preview/staging
[context.deploy-preview.environment]
  NODE_ENV = "development"

# Funciones serverless (si las necesitas más adelante)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Configuración para formularios (si los usas)
[forms]
  settings = true

# Configuración para imágenes
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"